### ISSUE TITLE
There are two PaymentService Producer instead of one

### ISSUE THREAD

**Issue by alexsalvo1** [confluentinc/learn-governing-data-streams-exercises#5]
I have run the code and when the lineage is generated there are two apps called: **PaymentServicePaymentSucceeded** and **PaymentServicePaymentFailed** instead of on **PaymentService**.

So in the lineage, instead of generating a single stream where the app PaymentService send event in the two topics (PaymentSuccedeed and PaymentFailed), you are generating 2 streams with two different apps writing in one topic each other:

- PaymentServicePaymentSucceeded app write in PaymentSuccedeed topic
- PaymentServicePaymentFailed app write in PaymentFailed topic

This is wrong respect the initial goal!

**Comment by WadeWaldron** [comment]
Thanks.

Yes, you are right. There was a change introduced recently during an upgrade to the code that causes this. Working on a fix and will hopefully have one ready soon.

**Comment by WadeWaldron** [comment]
@alexsalvo1 Thanks again for the heads up. This should be fixed now. Let us know if you encounter any more issues.
